import Head from "next/head";
import Header from "../components/layout/Header/Header";
import Footer from "../components/layout/Footer/Footer";
import "@/scss/index.scss";
import { ThemeProvider } from "@/context/theme";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

function RootLayout({ children, title }) {

  return (
    <html lang="en">
      <body >
        <ThemeProvider>
          <Header/>
            <main>
              {children}
            </main>
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;